#!/usr/bin/env bash

# flashso="/usr/lib/PepperFlash/libpepflashplayer.so"
# flashversion=`strings $flashso 2> /dev/null | grep LNX | cut -d ' ' -f 2 | sed -e "s/,/./g"`
# vivaldi-snapshot --ppapi-flash-path=$flashso --ppapi-flash-version="$flashversion" --proxy-pac-url="file:///home/amos/dotfiles/pac.js" --user-data-dir=/home/amos/.config/vivaldi "$@"

# /home/amos/softwares/qt59env/bin/python -m qutebrowser --backend webengine "$@"
/home/amos/softwares/qutebrowser/qutebrowser.py --backend webengine "$@"
